apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: certmanager
    annotations:
        kustomize.config.k8s.io/behavior: replace
        kustomize.config.k8s.io/needs-hash: "false"
data:
    api-token: ENC[AES256_GCM,data:BTG0AOaF/nqrQwIixdjUYb0BAnP8kmKkQM+4q4RMzNNqPOXXgxCzMi4L2cgZKNXOlqCCovSt8SI=,iv:1Fd2A7RA8LhpiccvaTvcEGM2oM3r1sUHsnRrPGGW4+Y=,tag:UFDheO29ESyim7+hiwIayQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaGZ3WnlreG1WV01OVXJm
            Y3JvQitwNWh0UENmNGpJU3ZCTUpLUUJzbWhZCnFqc25mTjNBVkpXVTRzK3RrL2VN
            SFVsQ3pLbmI1aGY3cDRIYWE4K1UrL0UKLS0tIFlhbk5OSjAza3p1ZzJZbmhZSG8z
            Vm9WYnZidE1Hd0xtVmxBaWVsaDh5SWMKCeABhi+TXhZok8bar/+LKs0s8ArHRwWM
            rooaommB690GFIsv0VGKlQQASLb7IOZWJqc8fHus8jfw9B+FZriLGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeHhaQXc5MWpWWFNrU0dZ
            dTNhc2dlaU5CVXYvSC9majhzZ0dVVm9nOEdrCklFQzdValNXanlkd0FrVy9NdFhZ
            VXZtSUlObmI1cjd1WDFTQ2VmeXdzSVEKLS0tIDQvSlVLUU81YTVBNG91OWxCN3Rh
            V1FCVE1abXV1ZU9ndXhrVFZzV0E2WmMKcNK6S443+uvaLbpI41J0QJ7qNXPT9+O+
            qnoMkO0iK1z6iMB+yhnKcoPMW8FZddO/zZP8JpVOT5GSfzWF9uflow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T15:54:40Z"
    mac: ENC[AES256_GCM,data:MspiaZW4H8GpHORZlftwH0j4S/v2CwKsfe1Co3SAVaI1cHRpszBRWAwEgE60jF7GusLQ8mUfsq1cAUYs7PBYRKYsp7c5Opxn7gLPKQC3mK5aQpgT42OiqUv78Nh7kWSkygKXFFfXAWqpyLkFZ3gjKkfIxCZ2dHn7ZNB/BzHXx9U=,iv:sGg5LVhS5O+4kA9ZxRaKYTFEH/hs6o2SGIR0rB2AwQo=,tag:Behe7mh6CbraMLqUcMsgzg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|clientSecret|argocdServerAdminPassword|oidc.config|commonName|literals)$
    version: 3.9.0
