---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - cloudflare_issuer.enc.yaml
  - wildcard.enc.yaml
  - secrets.enc.yaml
