---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - k8s.cloudflare_issuer.enc.yaml
  - k8s.wildcard.enc.yaml
  - k8s.secrets.enc.yaml
