apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-emby
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:W+SMPO0P5T+eACflhFg=,iv:atIpO+cd8JZ6WL04PpAHPpcMUD2Kt3AJN1VmAjC6evc=,tag:EKBfrXX56bA8XLzkEZ1E3A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:1xezV2oLZhcu3rNuWek+fJO90yo1iZCXeIEaWq6/ax+cBwzfJf0PVH37YuFkc4WHIZJbftR1603KttizDg==,iv:+MVMVnoKpF5r9PF1ww5vBJEoUkZ/TN4WRVnsS15tA1Q=,tag:oJxAfjBbQwYDUApxlYmlAw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:hlZS713RNRsrr4ZivdlSesYPPkL18E4tjKtolecVOdE/ODFrmvz8uQUXOFTkU+wa4cMfILfQiApA8Wt3SjqE5A==,iv:2Cdsrp8pQwXdxt48ZqDzKBhdjbZxb+X3Ed6fVH77DBk=,tag:nYEqZN/KZP2NCsJpnsbUYw==,type:str]
    RESTIC_ADDITIONAL_BACKUP_PARAMETERS: ENC[AES256_GCM,data:M806FzYWYT2KR3JOm239eafIS6+Zg3W5p8kJgFkArVizdjKssw==,iv:AFChOJS8BddmKis2/pBoOQxWM7DHhg85CKX37pZo6Vg=,tag:UMF5/iZ8To2APOHQbY8LMg==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:+p6qlLk=,iv:UYGxNg0FuRxSp90QkO1vrJoaqPJ0+0UCyFHa4Vi/UcU=,tag:qmAkeJ232jmB8iRyGyDQ+A==,type:str]
    KEEP_HOURLY: ENC[AES256_GCM,data:S5Q=,iv:esj0imcLMdM+U7bjtMFe+XxnuPpVYHwj+Jtffc4SwoM=,tag:c83ohQlSr3P2zqmrz8hFuA==,type:str]
    KEEP_LAST: ENC[AES256_GCM,data:pA==,iv:woipyEStWU0bs0DowQ4U8fBebr1cK8XCh+1VR6m5CN0=,tag:k6m+IlzTmfrI5KDn/6WJVg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:01Q2dGz/4deOlQVWnlT78FBY1U0=,iv:LPfk9FsocaTt/OTBegUFwwlVhY8jCuhPSuK8UzgGRNg=,tag:pdx0xCJEeewAZ0khuEA/kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+cCDBYu0BCF7TpQ7xr5VZ+3/7ruP7/KiVXL+xfpop8ZhLO2EaakT+g==,iv:RkXmD6o76v8cAtaVdf6e6qSlnLKlgKV/BdBTc85ob74=,tag:jnMh6vS+ijNNBqd6+p16Bg==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:Ykf8EA==,iv:H9vjA9forcfqqOC8LRYzmc4AimHX+N+qLZ36zTFDjCk=,tag:LlVQhxYMKEfXD1CEiMxorQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:B5aw92mvThcG9YYbRzDZjUE2+Jo3y7C0+UyY82XIZkBkVeRSwRiKhlzBGXp03HWASmaI+SIhn3OgZHKMkHC+K6emIGj3P0pjBMWS,iv:NPgwiTY/Wy2RHEYmYfuImwOS3DLJkRoUjIfKkDtfybA=,tag:1sizg2MkVpsZD3Y3MDbaxA==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:ShV/nOfbaqCrfN+LI7GGWQKV6DDLeqDvVah9,iv:VZylsOv5HfAKe9kUYlyqcQoezHcd3IZ5Qn1FtdmAJg8=,tag:ovA4gWBU+uSPm5mXY7kHtg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:XJJ5slJNIDJmM09hw/HMKOyj,iv:npxFebz0OO/b3ygJY8vu9Jd5ZB5cTTV17rzUKXIVwNo=,tag:6rixx5arX6QK8hm1//KHqw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:dox1Lg==,iv:f31pkko9atMUrW3li4bSM6aV5d1GdJux6x7qIkTgDTM=,tag:VfPHyo+nkLE2uaq8mvxplw==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:8FUXAMDHGDnHJwkBAW7KglVMkzV8LPvU02P19tJVok8CreKLQP0yVvfrml8T6OOTY1pjXmu1Qrd3HpLH0grj,iv:0D92j34vxKJoZofQYMoObJeQR5+7w2iJZmQK/H97AS0=,tag:XT+i6kgoq6HYG7ND8MHFqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFVFaWo4Z3EvT3hPUk94
            U1o3anpGQXJ1MDhRakJiRXpubUoyUkF4Z1dJCkY1Wkd3UHpRTnFndzJUQzkxR3JE
            aTlzVlk5UGxFaHF4YUxEYzljZHZnWGsKLS0tIGpjTzhIWmlHRlhpNlZFVk9VY2FT
            RmE2MElFQU85M213MDlJdkM5R2s0d28KfBQ6QMrqmBqkvvegFW5ALqujtFePR3Ju
            Pv9uhSTGmFdJeG1yJkg5dpZh1e03sv6kNXr2jF9ku87Sy240XhMkQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUtKMmJFZE5sWGY1cUpk
            cGpoMjJPL1luNm0zNUJ5dlhnWWFOL3ByQldRCm9zdlJ4V045Qk9wcTdTb2JzTHNm
            Q05zaTRqNW9KdlEzWXh5MGk0aHNpQTgKLS0tIEZWeEIzL0wveEErSjdFUndoTTlM
            dGlYeDg1eWFvQXRLWEY5My91NGUvTU0KE5B8lOzb3RHkrNlZidvixjbX9RYGC+uc
            a0UIHTJgMWEmfRd9Oo1q4e9pGQhd0qFDpzfahXA81oucrwFLC9mjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T20:08:07Z"
    mac: ENC[AES256_GCM,data:srFcNM8oc/9vlbbHsurCOH1FehXPd8of8LyXjETLIZhP7xUdcKoYa22mZE88CC/albH8RU2+Z5HZSYqPPNTRFVqj+fZQWqoJkaf6AwT32rSzbKtzQ+RPgym148enIe7sBMVrESB29SVv8Kb4NZbGZBUmF+nbHlfqkLDe2w4vyuE=,iv:qvZ6MY8LItXwTQOFzsmIIT1FHglUifSpSMzP1+PGJmg=,tag:DbMKhJ+69TpQcwubo1dRGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: crontab-emby
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
data:
    crontab: ENC[AES256_GCM,data:/3owIXnFMgP/E/HntA33ip/UZHUnPFyD77b6b7gVss0hTuim3C4O+Kjt3mp8pCr3aFU=,iv:a5AZPX227kOsqiFHBw0Mwp+S4ALjhzRRviK2qMXm/54=,tag:3MRXp9cIXEI2cqMjY+1E7Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFVFaWo4Z3EvT3hPUk94
            U1o3anpGQXJ1MDhRakJiRXpubUoyUkF4Z1dJCkY1Wkd3UHpRTnFndzJUQzkxR3JE
            aTlzVlk5UGxFaHF4YUxEYzljZHZnWGsKLS0tIGpjTzhIWmlHRlhpNlZFVk9VY2FT
            RmE2MElFQU85M213MDlJdkM5R2s0d28KfBQ6QMrqmBqkvvegFW5ALqujtFePR3Ju
            Pv9uhSTGmFdJeG1yJkg5dpZh1e03sv6kNXr2jF9ku87Sy240XhMkQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUtKMmJFZE5sWGY1cUpk
            cGpoMjJPL1luNm0zNUJ5dlhnWWFOL3ByQldRCm9zdlJ4V045Qk9wcTdTb2JzTHNm
            Q05zaTRqNW9KdlEzWXh5MGk0aHNpQTgKLS0tIEZWeEIzL0wveEErSjdFUndoTTlM
            dGlYeDg1eWFvQXRLWEY5My91NGUvTU0KE5B8lOzb3RHkrNlZidvixjbX9RYGC+uc
            a0UIHTJgMWEmfRd9Oo1q4e9pGQhd0qFDpzfahXA81oucrwFLC9mjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T20:08:07Z"
    mac: ENC[AES256_GCM,data:srFcNM8oc/9vlbbHsurCOH1FehXPd8of8LyXjETLIZhP7xUdcKoYa22mZE88CC/albH8RU2+Z5HZSYqPPNTRFVqj+fZQWqoJkaf6AwT32rSzbKtzQ+RPgym148enIe7sBMVrESB29SVv8Kb4NZbGZBUmF+nbHlfqkLDe2w4vyuE=,iv:qvZ6MY8LItXwTQOFzsmIIT1FHglUifSpSMzP1+PGJmg=,tag:DbMKhJ+69TpQcwubo1dRGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.0
