---
namespace: authelia

commonAnnotations:
  argocd.argoproj.io/sync-wave: "10"

helmCharts:
  - name: authelia
    repo: https://charts.authelia.com
    version: 0.9.14
    releaseName: authelia
    namespace: authelia
    valuesFile: values.yaml

resources:
  - namespace.yaml
