apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-nextpvr
    namespace: media
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:W+SMPO0P5T+eACflhFg=,iv:atIpO+cd8JZ6WL04PpAHPpcMUD2Kt3AJN1VmAjC6evc=,tag:EKBfrXX56bA8XLzkEZ1E3A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fUVRQYoUtIDo8C6fwJh+7WO2sP8DOIPPRQgYhy1TzT1e+tk3/TxgKtNHr+dJC8QvpOdyevuZrw==,iv:kGlcW+MhhpzLJKeEI65/xlGc6rqge6pS3JGd2YnrOrU=,tag:2O4k5IElBrwpk/DsPsPa4A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:vMwV4puCEUxi2TMyUftFYtpPS6WmTAIWcnbY+hsXCUpATz3Oy/jQEtuMcu9MZW1Y/6eTFZT1dalHaLjg7pl/rw==,iv:EdckdV4UhaBnttuaaoeXIiUhCAznwd0bnCk+GGzzSNA=,tag:yMyNDupU535x2up/U5wSWQ==,type:str]
    RESTIC_HOSTNAME: ENC[AES256_GCM,data:WTkk3RFdRQ==,iv:/KDwI0nUGwERSyxaK+2rTjdGcyynqiUlqZf6V50KA3I=,tag:2On6q77LEa/yhni62kY/2g==,type:str]
    KEEP_HOURLY: ENC[AES256_GCM,data:S5Q=,iv:esj0imcLMdM+U7bjtMFe+XxnuPpVYHwj+Jtffc4SwoM=,tag:c83ohQlSr3P2zqmrz8hFuA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:01Q2dGz/4deOlQVWnlT78FBY1U0=,iv:LPfk9FsocaTt/OTBegUFwwlVhY8jCuhPSuK8UzgGRNg=,tag:pdx0xCJEeewAZ0khuEA/kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+cCDBYu0BCF7TpQ7xr5VZ+3/7ruP7/KiVXL+xfpop8ZhLO2EaakT+g==,iv:RkXmD6o76v8cAtaVdf6e6qSlnLKlgKV/BdBTc85ob74=,tag:jnMh6vS+ijNNBqd6+p16Bg==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:Ykf8EA==,iv:H9vjA9forcfqqOC8LRYzmc4AimHX+N+qLZ36zTFDjCk=,tag:LlVQhxYMKEfXD1CEiMxorQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:B5aw92mvThcG9YYbRzDZjUE2+Jo3y7C0+UyY82XIZkBkVeRSwRiKhlzBGXp03HWASmaI+SIhn3OgZHKMkHC+K6emIGj3P0pjBMWS,iv:NPgwiTY/Wy2RHEYmYfuImwOS3DLJkRoUjIfKkDtfybA=,tag:1sizg2MkVpsZD3Y3MDbaxA==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:ShV/nOfbaqCrfN+LI7GGWQKV6DDLeqDvVah9,iv:VZylsOv5HfAKe9kUYlyqcQoezHcd3IZ5Qn1FtdmAJg8=,tag:ovA4gWBU+uSPm5mXY7kHtg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:XJJ5slJNIDJmM09hw/HMKOyj,iv:npxFebz0OO/b3ygJY8vu9Jd5ZB5cTTV17rzUKXIVwNo=,tag:6rixx5arX6QK8hm1//KHqw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:dox1Lg==,iv:f31pkko9atMUrW3li4bSM6aV5d1GdJux6x7qIkTgDTM=,tag:VfPHyo+nkLE2uaq8mvxplw==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:8FUXAMDHGDnHJwkBAW7KglVMkzV8LPvU02P19tJVok8CreKLQP0yVvfrml8T6OOTY1pjXmu1Qrd3HpLH0grj,iv:0D92j34vxKJoZofQYMoObJeQR5+7w2iJZmQK/H97AS0=,tag:XT+i6kgoq6HYG7ND8MHFqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFVFaWo4Z3EvT3hPUk94
            U1o3anpGQXJ1MDhRakJiRXpubUoyUkF4Z1dJCkY1Wkd3UHpRTnFndzJUQzkxR3JE
            aTlzVlk5UGxFaHF4YUxEYzljZHZnWGsKLS0tIGpjTzhIWmlHRlhpNlZFVk9VY2FT
            RmE2MElFQU85M213MDlJdkM5R2s0d28KfBQ6QMrqmBqkvvegFW5ALqujtFePR3Ju
            Pv9uhSTGmFdJeG1yJkg5dpZh1e03sv6kNXr2jF9ku87Sy240XhMkQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUtKMmJFZE5sWGY1cUpk
            cGpoMjJPL1luNm0zNUJ5dlhnWWFOL3ByQldRCm9zdlJ4V045Qk9wcTdTb2JzTHNm
            Q05zaTRqNW9KdlEzWXh5MGk0aHNpQTgKLS0tIEZWeEIzL0wveEErSjdFUndoTTlM
            dGlYeDg1eWFvQXRLWEY5My91NGUvTU0KE5B8lOzb3RHkrNlZidvixjbX9RYGC+uc
            a0UIHTJgMWEmfRd9Oo1q4e9pGQhd0qFDpzfahXA81oucrwFLC9mjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T12:38:01Z"
    mac: ENC[AES256_GCM,data:DG/nXdZc3hAMdd8PGDz27ZayNvuO0KSXvc+pJPWR0pFLWNHMLrNFrWoMYazg5clyDZ966u+5/EQGPkwuLniGD8hOuizxtccR6k8cb5hDya37CtUDASZYY86m2KW1szk6wcJCtBLIs/SYzdMGxA/grjfcauuh25nsSfGUGXYClqM=,iv:l7GRLH+uAPPRTcTuq1qHJwJUzxgLS0p/jhkirBwSgBc=,tag:2iksaByteK+nz2hSyeSRBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: crontab-nextpvr
    namespace: media
data:
    crontab: ENC[AES256_GCM,data:rHSfb5V8PQsnoHyZ/dimVNiCZzlkG/KAjH2L9acEHe7RDEp3ZHw7yIgvYw==,iv:PGz9axzpnRBu/Fk1OE2lD9bfN/lNBQta1im5SoP4vjk=,tag:3Ce9+9+yvAW1sCg63nUtOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFVFaWo4Z3EvT3hPUk94
            U1o3anpGQXJ1MDhRakJiRXpubUoyUkF4Z1dJCkY1Wkd3UHpRTnFndzJUQzkxR3JE
            aTlzVlk5UGxFaHF4YUxEYzljZHZnWGsKLS0tIGpjTzhIWmlHRlhpNlZFVk9VY2FT
            RmE2MElFQU85M213MDlJdkM5R2s0d28KfBQ6QMrqmBqkvvegFW5ALqujtFePR3Ju
            Pv9uhSTGmFdJeG1yJkg5dpZh1e03sv6kNXr2jF9ku87Sy240XhMkQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUtKMmJFZE5sWGY1cUpk
            cGpoMjJPL1luNm0zNUJ5dlhnWWFOL3ByQldRCm9zdlJ4V045Qk9wcTdTb2JzTHNm
            Q05zaTRqNW9KdlEzWXh5MGk0aHNpQTgKLS0tIEZWeEIzL0wveEErSjdFUndoTTlM
            dGlYeDg1eWFvQXRLWEY5My91NGUvTU0KE5B8lOzb3RHkrNlZidvixjbX9RYGC+uc
            a0UIHTJgMWEmfRd9Oo1q4e9pGQhd0qFDpzfahXA81oucrwFLC9mjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T12:38:01Z"
    mac: ENC[AES256_GCM,data:DG/nXdZc3hAMdd8PGDz27ZayNvuO0KSXvc+pJPWR0pFLWNHMLrNFrWoMYazg5clyDZ966u+5/EQGPkwuLniGD8hOuizxtccR6k8cb5hDya37CtUDASZYY86m2KW1szk6wcJCtBLIs/SYzdMGxA/grjfcauuh25nsSfGUGXYClqM=,iv:l7GRLH+uAPPRTcTuq1qHJwJUzxgLS0p/jhkirBwSgBc=,tag:2iksaByteK+nz2hSyeSRBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.0
