---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextpvr
  namespace: media
  labels:
    app: nextpvr
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nextpvr
  template:
    metadata:
      labels:
        app: nextpvr
    spec:
      hostNetwork: true
      containers:
        - name: nextpvr
          image: nextpvr/nextpvr_amd64:latest
          volumeMounts:
            - name: config-vol
              mountPath: /config
            - mountPath: /vol_raidz1/video
              name: video
          #resources:
          #  limits:
          #    gpu.intel.com/i915: "1"
          #  requests:
          #    gpu.intel.com/i915: "1"
        - name: backup-sidecar
          image: ghcr.io/restic/restic:0.17.1
          envFrom:
            - secretRef:
                name: backup-env-configuration-nextpvr
          imagePullPolicy: IfNotPresent
          command: ["/usr/sbin/crond", "-f", "-d", "6"]
          volumeMounts:
            - mountPath: /backup/config
              name: config-vol
              readOnly: true
            - name: crontab-config
              mountPath: /etc/crontabs/root
              subPath: crontab
            - name: backup-script
              mountPath: /usr/local/bin/backup.sh
              subPath: backup.sh
      restartPolicy: Always
      volumes:
        - name: config-vol
          persistentVolumeClaim:
            claimName: longhorn-pvc-nextpvr-config
        - name: video
          persistentVolumeClaim:
            claimName: smb-pvc-video
        - name: crontab-config
          configMap:
            name: crontab-nextpvr
        - name: backup-script
          configMap:
            name: crontab-backup-script
