---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: longhorn-pvc-nextpvr-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
  volumeMode: Filesystem
