apiVersion: v1
kind: ConfigMap
metadata:
    name: rclone-config
    namespace: longhorn
data:
    rclone.conf: ENC[AES256_GCM,data:RflwK6COdXJ8ezK5+8pd0MAecY0NSBEWKqNXWR2ZQajVDvw4gbKYptW/J6CI8z4wGn4yD9/nIDlEBEunwcZ3K7gyVHC5G8DBkAZhAqbQGBUwRVSkqZNKUUpvOPBQdDFMIqwHK8bwvMV9h/liS9itmi8tTDmmYf1MHCJ7ovA4zVN3/OtKv/t+ZBtoZ64WKnhaOTs1UYLj3XRmMmnF0w7WIrVsda0nuGVaxClD1f615sqzow/9nWWuPWXR8faCAesQMajPH24i,iv:Qt9q+6JsE8Cuzr/OBhlr302JMScBBjukVdc9tPyWsuE=,tag:54nv2IrVx5Q0/2ZzFZPEWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQmJFMjBXWkVkM0RCanFv
            OGdBYTJvZWgrZ3pRUE02aFoyVlFidG51aW1ZCnRENEFyc1VuOUQ2M0JSdlcwS0lO
            ajRTN2sycHFTVCsrY0ZielhuWkkwT0EKLS0tIGFKdXlrZ21YMkFuRHQ4aVJNNnZV
            QWZEd1JXUWx2ZmorMFYyUkYyR1J2b3cKgQBxx4kGfmBta5UPthrMHupOOdG+egAC
            CKCcD7Hlm4TiymT8N5f6389EZMYLgvsqpEElV1oBJRbSD8++aOu+qA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVWFRZkFEa3k1WmtJN2lN
            UFRWakg5NmRWYjBzR0s0NlN3NnhVSjVMQTNNCnNYWTV6NUFMdFNQeVc1Mm9DbndS
            SkJtb0Q1RkVaaDFOakxPRWlZM3lvZHcKLS0tIE1pbExHVmxpNy9Jby9jdGxNZit4
            SFliMFROOStLT3IrT0Y0VjJwVzdhMHMKb2smvDjwAYLUSI8Gs5aIUFG+JyFIexcv
            yDaCc7Ic2/7EM471x5tiPobArVqYU5s9Y1zTyIPNadwVDXViKs9OXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T07:35:24Z"
    mac: ENC[AES256_GCM,data:GyiETVoEYBKL7m2eaGAV6UWMz4Pz+KNnZ8GRHJtJi+6fGS/ES+nPf5+fJBzJ0HKbMeSUAicZ4BLeQ8Sm42WxgQAd7WlM82DIxhxmLXUlj8aieXsYgTTRofYoXGRd8+FbkkSBLyBCkkbQwuLB0hgoFY4amsL0GJLy458V1wmJvEY=,iv:k9vaw9MlxCbAUarMtB8MXmET8D8oRMSZj4Wko0pGMvI=,tag:8nVjnjAbgLWJ1I9C3xn16Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.1
