apiVersion: v1
kind: Secret
metadata:
    name: restic-backup
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:5ku7c9izPgLGCZfSloH+LqAA6ET+5UiOxu3XgOlVXx9MNyWM2f2txjBnLdywVK02JVHWKhoW8f60b9u8Ew==,iv:CtX/XNwyJcSTuoNKj92aB+fXcnuL8rr0jl6S9gur+kA=,tag:Cg62N+gtdA13/soB1BwOFw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:x0WPaQLgRQXvX3zz4olu51wq4rEYmxqe2a5jOjUGeH/00xexfqnY/63Z/+pXZoEAa5xxpRsb9R1OqLoLrGHREg==,iv:netJv7XQkYon+Fk+r9I+iB1K2kN+rvTzwvjvttOCfw8=,tag:JuKWCJ4hXYgcka5VybmRkA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:raZJN9gwuKe+lzCkIAXaGMz/XuY=,iv:JxzxgfmH6azob+xvkM2CI/bdeM79j286NLghUAgSMyM=,tag:tubNrU/IgoEWkKMtOYhkZA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uaGGvvZWf0xGoaGzQOxKpcsVGNrsBPJQoqc9drTOV4ruxiXyZHFuWQ==,iv:HDkKwRqNRYqdSGBde0EuOzfuD45jDeV+pASkwYYcJTU=,tag:p9KV8vgAW3PmeeXYbMoZcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S2JRVE0yeVpaOTB6cmVZ
            M3B0ZCtTNk85TEM1c3U5OXA1MkhQUzJKMmxnCmJsaGlvWEdwSHdpdjJ5dHBYNFhq
            NVo1UzNVVXVqU0VSS0FTb1VoVjhPeEEKLS0tIFlIQzN1ZTZjMWo0WEdxRWE4azRr
            YlFkODN3SzJBQVlUMFdSbXJBa2UrZ3MKYqapBKWHF/hfbeMh/NrG1VaHhpb6kwfj
            V9VcclHf6rxvgCVINAm09+3Zf+nXi4pAGk3cHbcBTw8wpDy/qcPfGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNkZiUmJWZVIxSDZET2Qv
            Z0FzWHpsM200UzJ5Q0ZmMmVtalJsdnhwd200CklGOGxiM0M5WHQxMTB5Nm9LZWlR
            WW96Z2JaZjVYSkFZT0VvZ0pyTEpJUFUKLS0tIDNyQmhOL0hDR1BoTEphZGIzZ3gv
            NzREVHBQaXF6REkwTkJ6TkwzbVNUN0kKretAGso/z37pmGGvviJbcfN4nkMDDQtw
            2CRJmRs8A65IZQ8GFUH9U/n60TlMc83ya/Hb6X+MegRqQuiESMsjzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T22:23:06Z"
    mac: ENC[AES256_GCM,data:lcxgz+68HACTF3YVe3Y/VjzuSr8dLiGN9LY1qO9vJZB/TDef1XDKptrI0dhllNzgaPpIlZ5oGvQxpONkRp1d9k1Y/QXuUH/IV6py/Xj6C5+6jrp//5eqxGkFtalxkAlETGXnDCcdesaRqonojkrlN4h+JxaNiq192tt2hrdKKFc=,iv:rJuAQ2P+b1P0cpHLbsl4qcuGYNGxxI3R6pjReStrT5s=,tag:+/0+v5GG6A9StgNiha2BCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.1
