apiVersion: v1
kind: Secret
metadata:
    name: restic-backup
    namespace: longhorn
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
data:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:NyoNb1qcuRSS+gtM+uvk04P6+M0eyK302WZJmEsg7Cz9co3uW6slIyW5OrHpmcFG6XNZmuD8SDJtBFXWE3wqsUFiuXtF9yFBTsRdrqC4etkOoRZQ,iv:1RRgpA3UhTbBEweGJLL5mjYxQ6NFJ1htC3oXYun7cx0=,tag:8ICju7CYmY2tN/VYZDCjpQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:lxEwRdk/uRMDTL5QTlO+0YkB3xog6xThgojNyodFBPKW4Zpsgl3eqqoc/2H59xXoFXGf77NAlfnFXWTk8QTA/K/bEz26bt13cGkCYH5a0nBPi5Jhc4qnaw==,iv:ikYU9I2NY6XkFT1KvkCcE5o9/MbfHrXPU7raWASebf0=,tag:kRCM5xunFWDKD3Woq2BpUw==,type:str]
    RESTIC_CACHE_DIR: ENC[AES256_GCM,data:bWH5ZvleaLTmjs8AkheZ5A==,iv:YVUwilAYLXA5Dsf7rI5VxonBE5IqcxXv96hrliyiMfk=,tag:tuP3n64/Z78ZHrf0s2R3Lw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rrL8yVVnk8ohfTLh85hCAY2jbXXzkP/8pOn+zA==,iv:tch8jlfrbgx9AVtXWaVkesrOfeRnp+1OTaA9OKHRQH4=,tag:MnOX+wZkDPdDAN/OiFYXYQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:od9NM7cN6VAysEU0U1HgGWrHBubUwuKMcr5gZ6hHUIwz1sD/ZVcCafCux1AjBCgiYMIX6geV32M=,iv:vvGFZkwIYN9MPqY+vY9DKt0hzgvTpLl9rlkdTymU/CI=,tag:BEKPUtdA5dFKH0f8qaFH7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S2JRVE0yeVpaOTB6cmVZ
            M3B0ZCtTNk85TEM1c3U5OXA1MkhQUzJKMmxnCmJsaGlvWEdwSHdpdjJ5dHBYNFhq
            NVo1UzNVVXVqU0VSS0FTb1VoVjhPeEEKLS0tIFlIQzN1ZTZjMWo0WEdxRWE4azRr
            YlFkODN3SzJBQVlUMFdSbXJBa2UrZ3MKYqapBKWHF/hfbeMh/NrG1VaHhpb6kwfj
            V9VcclHf6rxvgCVINAm09+3Zf+nXi4pAGk3cHbcBTw8wpDy/qcPfGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNkZiUmJWZVIxSDZET2Qv
            Z0FzWHpsM200UzJ5Q0ZmMmVtalJsdnhwd200CklGOGxiM0M5WHQxMTB5Nm9LZWlR
            WW96Z2JaZjVYSkFZT0VvZ0pyTEpJUFUKLS0tIDNyQmhOL0hDR1BoTEphZGIzZ3gv
            NzREVHBQaXF6REkwTkJ6TkwzbVNUN0kKretAGso/z37pmGGvviJbcfN4nkMDDQtw
            2CRJmRs8A65IZQ8GFUH9U/n60TlMc83ya/Hb6X+MegRqQuiESMsjzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-27T11:38:33Z"
    mac: ENC[AES256_GCM,data:xiymhsQefFENvbYFg6Km65QzxCqnngxAj7YULvSiq36+E9TColBh9a8g9bIXTAKc04P54kFfZbse4af3zc/bmz86IQosrRKk5IjmR9830G+aO8Nyp5IyJ6/JHNuyYE9Y8AAM/7bwY9CJlmwh6s4qmkQ5zuhhfAWoLN6CrMkHtmY=,iv:7oPgKC7ei97el0dZXG4dZbsd5h+cGuS2PJFa2AuSwCI=,tag:eVxUcSSYfqoks+L8018bFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.1
