apiVersion: v1
kind: Secret
metadata:
    name: backup-env-configuration-mariadb
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
stringData:
    RESTIC_SOURCE: ENC[AES256_GCM,data:W+SMPO0P5T+eACflhFg=,iv:atIpO+cd8JZ6WL04PpAHPpcMUD2Kt3AJN1VmAjC6evc=,tag:EKBfrXX56bA8XLzkEZ1E3A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:qP8ABalppRwme7XBTKKEO7rytpk855sHuGddrVIXk5JOpmGbbJ2inB8QZlS4mydVkYvdgp2LWOLP87xTVw==,iv:heUgsM+kNSF2bGD/kfecgsBbdPmRwBtc3CYkOqGTZYk=,tag:wXLHZetMrJKsejMsFWgtjA==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:tYJnvidUGRee76Fx/0BG4Fyo5OvZxa/fptkIcQTfm7ybbIRxgxIM2yeVKNA6+WSDvedW3NXMykjs6Kf+Kl+Qog==,iv:rO3p8umYNt9GGbBgQ8lJ8KcvI9lcEROeecCsGJzphfY=,tag:NWxfyr4cl3kOdj1w5zlrzg==,type:str]
    RESTIC_RETENTION_POLICIES_ENABLED: ENC[AES256_GCM,data:Vv+EWfM=,iv:BHn/ExtKQr6nteXghbvitmPnHnwfmoVLSbVE7XpBkok=,tag:DwwttteWtv4G5Nn719czhA==,type:str]
    KEEP_HOURLY: ENC[AES256_GCM,data:S5Q=,iv:esj0imcLMdM+U7bjtMFe+XxnuPpVYHwj+Jtffc4SwoM=,tag:c83ohQlSr3P2zqmrz8hFuA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:01Q2dGz/4deOlQVWnlT78FBY1U0=,iv:LPfk9FsocaTt/OTBegUFwwlVhY8jCuhPSuK8UzgGRNg=,tag:pdx0xCJEeewAZ0khuEA/kg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:+cCDBYu0BCF7TpQ7xr5VZ+3/7ruP7/KiVXL+xfpop8ZhLO2EaakT+g==,iv:RkXmD6o76v8cAtaVdf6e6qSlnLKlgKV/BdBTc85ob74=,tag:jnMh6vS+ijNNBqd6+p16Bg==,type:str]
    NTFY_ENABLED: ENC[AES256_GCM,data:Ykf8EA==,iv:H9vjA9forcfqqOC8LRYzmc4AimHX+N+qLZ36zTFDjCk=,tag:LlVQhxYMKEfXD1CEiMxorQ==,type:str]
    NTFY_CREDS: ENC[AES256_GCM,data:B5aw92mvThcG9YYbRzDZjUE2+Jo3y7C0+UyY82XIZkBkVeRSwRiKhlzBGXp03HWASmaI+SIhn3OgZHKMkHC+K6emIGj3P0pjBMWS,iv:NPgwiTY/Wy2RHEYmYfuImwOS3DLJkRoUjIfKkDtfybA=,tag:1sizg2MkVpsZD3Y3MDbaxA==,type:str]
    NTFY_SERVER: ENC[AES256_GCM,data:ShV/nOfbaqCrfN+LI7GGWQKV6DDLeqDvVah9,iv:VZylsOv5HfAKe9kUYlyqcQoezHcd3IZ5Qn1FtdmAJg8=,tag:ovA4gWBU+uSPm5mXY7kHtg==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:XJJ5slJNIDJmM09hw/HMKOyj,iv:npxFebz0OO/b3ygJY8vu9Jd5ZB5cTTV17rzUKXIVwNo=,tag:6rixx5arX6QK8hm1//KHqw==,type:str]
    PUSHGATEWAY_ENABLED: ENC[AES256_GCM,data:dox1Lg==,iv:f31pkko9atMUrW3li4bSM6aV5d1GdJux6x7qIkTgDTM=,tag:VfPHyo+nkLE2uaq8mvxplw==,type:str]
    PUSHGATEWAY_URL: ENC[AES256_GCM,data:8FUXAMDHGDnHJwkBAW7KglVMkzV8LPvU02P19tJVok8CreKLQP0yVvfrml8T6OOTY1pjXmu1Qrd3HpLH0grj,iv:0D92j34vxKJoZofQYMoObJeQR5+7w2iJZmQK/H97AS0=,tag:XT+i6kgoq6HYG7ND8MHFqg==,type:str]
    RESTIC_BACKUP_COMMAND: ENC[AES256_GCM,data:1XiLA92bDo3i/ONWDzo6yEz96IEe4xa04wOL5P4do9Qxio6M1BBaCh/NqEW9rH2BfgAsCTCJu4ZWyWEHOKn5KBf5QfM48KDvcW4cAOipVLuoTbdCiaK2VbSmnyBYInt8wPo+sbx3QUf10g5lyKkrPqksr82r2ZQX8vmpXVx8W4JCtnQgwmI80hq4ZNQSdj7ZYK6b7d5n0d3Hc9Vor1XNqpmg7IzQ0eyUIyx4x/5Ym9V/ER0ja1ANaSLehPsYrF+XPvbyKeAc6rqasbAkk59ku6cHxOlMgCj3RA==,iv:4RT4UKpevPksng4wVoHoezP8KkFL9nznniAle4A1m84=,tag:T6XhckblCrTEt1PQ60W7tA==,type:str]
    PRE_HOOK: ENC[AES256_GCM,data:lryXQRCbfowg7Lomh1rx0HGiY3XOzXaVm4DiSs9DgqXtKue813w2oRErXMdHnTolc4lBL+9ipmd6tRcw/E7W7++NaqFZ/r5M/FYnlY2FcmAZ0stDtHw3ytTLs4VOiXdBFw2yGxCcRWgm695MKDjTZUTMDSxia4qDDgskXdkUVZvxZtCme/G7aYSqQFYLM0UGBj66,iv:qDO1bUADE+CLFnWiB/PkTV/DTMF0CYo3QZ2YZpN4G3Y=,tag:3Xo6Mu+hMAzojMtQzYHutw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFVFaWo4Z3EvT3hPUk94
            U1o3anpGQXJ1MDhRakJiRXpubUoyUkF4Z1dJCkY1Wkd3UHpRTnFndzJUQzkxR3JE
            aTlzVlk5UGxFaHF4YUxEYzljZHZnWGsKLS0tIGpjTzhIWmlHRlhpNlZFVk9VY2FT
            RmE2MElFQU85M213MDlJdkM5R2s0d28KfBQ6QMrqmBqkvvegFW5ALqujtFePR3Ju
            Pv9uhSTGmFdJeG1yJkg5dpZh1e03sv6kNXr2jF9ku87Sy240XhMkQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUtKMmJFZE5sWGY1cUpk
            cGpoMjJPL1luNm0zNUJ5dlhnWWFOL3ByQldRCm9zdlJ4V045Qk9wcTdTb2JzTHNm
            Q05zaTRqNW9KdlEzWXh5MGk0aHNpQTgKLS0tIEZWeEIzL0wveEErSjdFUndoTTlM
            dGlYeDg1eWFvQXRLWEY5My91NGUvTU0KE5B8lOzb3RHkrNlZidvixjbX9RYGC+uc
            a0UIHTJgMWEmfRd9Oo1q4e9pGQhd0qFDpzfahXA81oucrwFLC9mjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T16:40:10Z"
    mac: ENC[AES256_GCM,data:F+tO1WQn+/Amv/V5sFajx2/Nrqz758vHu1ZluQI74NbO6GSsctXf+icMH/ib/z98krosfMahbfazI46VAstCnqQs+FSkXn46tfLxvMCBgxujxyVt9IddzkHFurH7NtcGmgCUY2dQhwmBZl72bkTHs57c6HxD3m/3P+TVpiwTORs=,iv:5KFqOae1WILVRTBzjmY+mVsWK+pR/gbrZpv1q2WbVS4=,tag:M3bOIr4wgJ9NL5pKNh7DFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.1
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: crontab-mariadb
    namespace: media
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
data:
    crontab: ENC[AES256_GCM,data:YKilsQ3rhBLGMP/fEWJ7dXKYAyVH9XK1slIz2VqCWpcMZT4U6z7HEpSYIw==,iv:qxfeWkmG05yakZwgiwL1Xqw4NDpShoCqqTi59QHrJIg=,tag:HTbfIHIH76AZLQWpYpbyIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSFVFaWo4Z3EvT3hPUk94
            U1o3anpGQXJ1MDhRakJiRXpubUoyUkF4Z1dJCkY1Wkd3UHpRTnFndzJUQzkxR3JE
            aTlzVlk5UGxFaHF4YUxEYzljZHZnWGsKLS0tIGpjTzhIWmlHRlhpNlZFVk9VY2FT
            RmE2MElFQU85M213MDlJdkM5R2s0d28KfBQ6QMrqmBqkvvegFW5ALqujtFePR3Ju
            Pv9uhSTGmFdJeG1yJkg5dpZh1e03sv6kNXr2jF9ku87Sy240XhMkQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNUtKMmJFZE5sWGY1cUpk
            cGpoMjJPL1luNm0zNUJ5dlhnWWFOL3ByQldRCm9zdlJ4V045Qk9wcTdTb2JzTHNm
            Q05zaTRqNW9KdlEzWXh5MGk0aHNpQTgKLS0tIEZWeEIzL0wveEErSjdFUndoTTlM
            dGlYeDg1eWFvQXRLWEY5My91NGUvTU0KE5B8lOzb3RHkrNlZidvixjbX9RYGC+uc
            a0UIHTJgMWEmfRd9Oo1q4e9pGQhd0qFDpzfahXA81oucrwFLC9mjSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T16:40:10Z"
    mac: ENC[AES256_GCM,data:F+tO1WQn+/Amv/V5sFajx2/Nrqz758vHu1ZluQI74NbO6GSsctXf+icMH/ib/z98krosfMahbfazI46VAstCnqQs+FSkXn46tfLxvMCBgxujxyVt9IddzkHFurH7NtcGmgCUY2dQhwmBZl72bkTHs57c6HxD3m/3P+TVpiwTORs=,iv:5KFqOae1WILVRTBzjmY+mVsWK+pR/gbrZpv1q2WbVS4=,tag:M3bOIr4wgJ9NL5pKNh7DFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.1
