# Persistend Volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-mariadb-backupvolume
  namespace: databases
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
