## Service Account
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb-backup-serviceaccount
  namespace: databases
## Role with permissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: databases
  name: mariadb-backup-role
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create"]
## Bind role and service account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mariadb-backup-rolebinding
  namespace: databases
subjects:
  - kind: ServiceAccount
    name: mariadb-backup-serviceaccount
    namespace: databases
roleRef:
  kind: Role
  name: mariadb-backup-role
  apiGroup: rbac.authorization.k8s.io
## CronJob
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mariadb-backup
  namespace: databases
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: mariadb-backup-serviceaccount
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  POD_NAME=$(kubectl get pods -n databases -l app.kubernetes.io/name=mariadb -o jsonpath="{.items[0].metadata.name}")
                  kubectl exec -n databases $POD_NAME -- bash -c "mariadb-backup --backup --target-dir=/bitnami/mariadb-backup --datadir=/bitnami/mariadb"
            - name: backup-sidecar
              image: ghcr.io/restic/restic:0.17.3
              env:
                - name: MARIADB_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: mariadb-root-password
                      name: mariadb
              envFrom:
                - secretRef:
                    name: backup-env-configuration-mariadb
              imagePullPolicy: IfNotPresent
              command:
                - /bin/bash
                - -c
                - /usr/local/bin/backup.sh
              volumeMounts:
                - name: backup-script
                  mountPath: /usr/local/bin/backup.sh
                  subPath: backup.sh
                - name: backup
                  mountPath: /backup
                  readOnly: true
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
                privileged: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsNonRoot: true
                runAsUser: 1001
          restartPolicy: Never
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-mariadb-0
            - name: backup
              persistentVolumeClaim:
                claimName: longhorn-pvc-mariadb-backup
            - name: backup-script
              configMap:
                name: crontab-backup-script
