# Persistend Volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-pvc-mariadb-backup
  namespace: databases
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
