---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: databases

helmCharts:
  - name: mariadb
    repo: https://charts.bitnami.com/bitnami
    version: 18.2.6
    releaseName: mariadb
    namespace: databases
    valuesFile: values.yaml

resources:
  - namespace.yaml

generators:
  - kustomize-secret-generator.yaml
#patches:
#  - target:
#      group: apps
#      version: v1
#      kind: StatefulSet
#      name: mariadb
#    patch: |-
#      apiVersion: apps/v1
#      kind: StatefulSet
#      metadata:
#        name: mariadb
#        namespace: databases
#      spec:
#        template:
#          spec:
#            shareProcessNamespace: true
