global:
    storageClass: longhorn
architecture: standalone
auth:
    rootPassword: ENC[AES256_GCM,data:bMMBdMb7hsMiGfUfwahUMiinV+ZClO0CBwH7O7np/OPLfFcmsiSkYZpr09HUF8ljGLScHgAsAwfL8cq3i+ZTiQ==,iv:LBXUPiA/eSz195Sc8dwNzPU+Z0PL52zX9dqtlZkoqi4=,tag:bBeLTGBDrLd43ISOlY9qFg==,type:str]
    replicationPassword: ENC[AES256_GCM,data:i6RIWLBNYe1kxYVFmMJ7Yp6Ha2gBBguS98irvdBeVlGMqHrz/+cqCcBXDHQUCzrs4wkZWa5QqmbZYhHNf+quTA==,iv:dJNWJsaVybNlREhYbQYyF8Wc3KjA0PvaI8ezhV3dRmE=,tag:0qsoEz4hjHho8tCLugLWgg==,type:str]
metrics:
    enabled: true
    serviceMonitor:
        enabled: true
primary:
    revisionHistoryLimit: 2
    sidecars:
        - name: backup-sidecar
          image: ghcr.io/restic/restic:0.17.1
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    key: mariadb-root-password
                    name: mariadb
          envFrom:
            - secretRef:
                name: backup-env-configuration-mariadb
          imagePullPolicy: IfNotPresent
          command:
            - /usr/sbin/crond
            - -f
            - -d
            - "6"
          volumeMounts:
            - mountPath: /bitnami/mariadb
              name: data
              readOnly: true
            - name: crontab-config
              mountPath: /etc/crontabs/root
              subPath: crontab
            - name: backup-script
              mountPath: /usr/local/bin/backup.sh
              subPath: backup.sh
            - name: backup
              mountPath: /backup
              readOnly: true
    extraVolumes:
        - name: crontab-config
          configMap:
            name: crontab-mariadb
        - name: backup-script
          configMap:
            name: crontab-backup-script
        - name: backup
          emptyDir: {}
    extraVolumeMounts:
        - name: backup
          mountPath: /backup
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTmVOTCs3YTF0VE4xTFZ6
            U29COG9jdmEyMW9wbmFjZ1duUnN2dG4yR1QwCmxVUHYyc3FlVkxZRm8yVzd6S2lO
            YkVHZHA0SjVOTk1aYXU1dWNoUmJ2dVkKLS0tIFlHWmZ2bHFEVVdvbUt1bGpSeFRD
            ZXdsZmY3WUpkdlZKQUY1WmFTZGR3ME0KicsNUFLthNJpPgbhU1kiSfLnGmHB1Rcs
            qw4keSQ1hvAX93zlgRrariQXkFvgec3ferift5JrZmQMYpPHfpRsYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrekQvMUVkTWlIM010c2NS
            ZnBJZ213SUwrRUdWenZCbG5jblV0eldXbW5BClRmMUV4SWZBdTlEVmdPR2I3SStS
            aUdDNDNFMXNLWmxyazJyL0JiMmlYdUkKLS0tIGQzTk9XQUlUTzhjWEdpOWFZcUNI
            eWkvQThOWWRzVDlmQlZzbU5tNkdyVUkK9bIBo70oaJK31myMDcpPdo5tWTN+JLB5
            2xqj5S1wzAyYII/d7ZfbhlLm9kwpvpnV4Wfl9unkMirspONq2VfdWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-23T17:27:36Z"
    mac: ENC[AES256_GCM,data:HjAt6m7U32cB2TJdDCoHbTSbO95nCNkL57uuNmWRGfTrR7TqSklo+BL92OzYg1pe0+CbNwVJJZUK3+TtITpFt/a/eC7DOG/9PgIoE0hTaL3nCSo4vEdrOq8ntCiwX0N/e9gkMYr/UmBXWrxtcHiwqFRf1GY0MDDSclqB/lD/tbY=,iv:DHt0fazQs0c32xH3QJgKDsQSxcNVQsfQbLAXIcroQfI=,tag:vvn5mAWxCwSj8XKTKhEEeg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword)$
    version: 3.9.1
