global:
    storageClass: longhorn
architecture: standalone
auth:
    rootPassword: ENC[AES256_GCM,data:bMMBdMb7hsMiGfUfwahUMiinV+ZClO0CBwH7O7np/OPLfFcmsiSkYZpr09HUF8ljGLScHgAsAwfL8cq3i+ZTiQ==,iv:LBXUPiA/eSz195Sc8dwNzPU+Z0PL52zX9dqtlZkoqi4=,tag:bBeLTGBDrLd43ISOlY9qFg==,type:str]
    replicationPassword: ENC[AES256_GCM,data:i6RIWLBNYe1kxYVFmMJ7Yp6Ha2gBBguS98irvdBeVlGMqHrz/+cqCcBXDHQUCzrs4wkZWa5QqmbZYhHNf+quTA==,iv:dJNWJsaVybNlREhYbQYyF8Wc3KjA0PvaI8ezhV3dRmE=,tag:0qsoEz4hjHho8tCLugLWgg==,type:str]
metrics:
    enabled: true
    serviceMonitor:
        enabled: true
primary:
    revisionHistoryLimit: 2
    extraVolumes:
        - name: backup
          persistentVolumeClaim:
            claimName: longhorn-pvc-mariadb-backup
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTmVOTCs3YTF0VE4xTFZ6
            U29COG9jdmEyMW9wbmFjZ1duUnN2dG4yR1QwCmxVUHYyc3FlVkxZRm8yVzd6S2lO
            YkVHZHA0SjVOTk1aYXU1dWNoUmJ2dVkKLS0tIFlHWmZ2bHFEVVdvbUt1bGpSeFRD
            ZXdsZmY3WUpkdlZKQUY1WmFTZGR3ME0KicsNUFLthNJpPgbhU1kiSfLnGmHB1Rcs
            qw4keSQ1hvAX93zlgRrariQXkFvgec3ferift5JrZmQMYpPHfpRsYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrekQvMUVkTWlIM010c2NS
            ZnBJZ213SUwrRUdWenZCbG5jblV0eldXbW5BClRmMUV4SWZBdTlEVmdPR2I3SStS
            aUdDNDNFMXNLWmxyazJyL0JiMmlYdUkKLS0tIGQzTk9XQUlUTzhjWEdpOWFZcUNI
            eWkvQThOWWRzVDlmQlZzbU5tNkdyVUkK9bIBo70oaJK31myMDcpPdo5tWTN+JLB5
            2xqj5S1wzAyYII/d7ZfbhlLm9kwpvpnV4Wfl9unkMirspONq2VfdWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-26T15:06:13Z"
    mac: ENC[AES256_GCM,data:b0e/yNntKrYhf2ZmJJ2aZPNZncrRiGBeQcMUH6a4t/RuDV1oU6liPt+5qA/boZnDVc5uXlrY91VYLhkhe5TEiTt4QXT4IrpdhpxI5pmI8fK6xzSp7MbxkmY7DhNZLDWbfWAmQpR5Khc8Eu774H1ohq1R5x5vw/ALjBhN5YoJnII=,iv:U3gCC0I8inQUBK+0lKil6krFQUD7HqWYALCrZzW2bRQ=,tag:Q93tODbVsFcq04DUpoEX0g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword)$
    version: 3.9.1
