---
# code: language=ansible

- name: Arch | Updating archlinux-keyring
  community.general.pacman:
    name:
      - archlinux-keyring
    state: latest

- name: Arch | Installing Packages
  community.general.pacman:
    name:
      - nano
      - htop
      - open-iscsi
      - k9s

- name: Arch | Installing qemu-guest-agent on KVM
  community.general.pacman:
    name: qemu-guest-agent
  when: ansible_virtualization_type == "kvm"

- name: Arch | Comment out DNS servers from vagrant image
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNS=4\.2\.2\.1 4\.2\.2\.2 208\.67\.220\.220'
    line: '#DNS=4.2.2.1 4.2.2.2 208.67.220.220'
    backrefs: true
    state: present
