---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 90-goldilocks
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "90"
spec:
  project: default
  source:
    repoURL: "example.com"
    path: apps/goldilocks
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
