---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 97-argocd-configmanagementplugins.yaml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "97"
spec:
  project: default
  source:
    repoURL: "example.com"
    path: apps/argo-cd-configmanagementplugins
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true
