apiVersion: v1
kind: Secret
metadata:
    name: lldap-credentials
    namespace: authelia
    annotations:
        kustomize.config.k8s.io/needs-hash: "true"
type: Opaque
data:
    lldap-jwt-secret: ENC[AES256_GCM,data:upWLnBKVJjjcu0R4wfmWzi84NyBdihMYor/ro53aHQwJY0dee8gwzaBi9zBmhqQDRlgK0aqqm7bw6f0tyRCUf5SnjJUETHCA7ihg10gLupk6j4zFYx8PTw==,iv:9z5dUeoc/vbQ1Vs1qtQ21W3+jlNuKK6IyxnUY3SlQOs=,tag:lzSplmYKoTZZdTCgaOgm/g==,type:str]
    base-dn: ENC[AES256_GCM,data:sAT8UtQ7pOIiWVVBAQjVXNjiew6LFRa0,iv:7r9GrEPj6eM6EtyCpPm0n5eQ+UeZq35Y/ifCNhN5QVg=,tag:wsP/Y0msWg38RiakrnzpDw==,type:str]
    lldap-ldap-user-pass: ENC[AES256_GCM,data:gdsgL+zag5mEQGgt9Qr3Ydwsb9Ghf+ghtAJd88iNBxR1lvR4yBJEy9kOWyot/PjyXA4e6JY7unsqsQG9gVvppOqS2E0rc5d0NeHfnL1kfNXWI7g55xC2rQ==,iv:6B1Pb9G5vXWWz1lq01XMeeI8AYp6HiqmS5WgSojN7Q0=,tag:X0l9E13K05qFp4dbKPwisg==,type:str]
    lldap-ldap-key-seed: ENC[AES256_GCM,data:2X/lErgxGqc/nOxSdDOGxJBo1yv78dDAz1vZkBid4E04s5clRNmVoJVMtRoHC4bvvibRoN99/WBQMhQiMn3RtXWhFkegsweP9PlZCFIusGUxAzl2bZ+x9Q==,iv:mqQbibSutGH/gQaH8UK9JhMcO3kgf8EK0tjQNrVF1tI=,tag:yt3hlZH8Cmm8NOH1EUIg2A==,type:str]
    lldap-database-credentials: ENC[AES256_GCM,data:w7jYNHUc66tJ05deMEujjLd3UVuT8Ln5TKn+HoNPAzm5iHvNRL/7su7XKZq6hJlMes3pQMVV4njX7jmRdOjeGeL+VMVXFgo64I6kKGDAY8l5lIEJRM16fOukruul2bKIATqNShM3TsoHaV85xG6qSJq+SwfB9Oq4Sj/bv1KAw7pIVTeW98X575q4NQy6qjM0bhgBDvjvdDa2wvJYh9R8aQ==,iv:sM1HYvKoJFzAtlGfoZ0EG3p8Pwro3A3mxU+yOILiSaI=,tag:xwUA06hBfrLSr1EocJrKMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0d2NnZnlubFV6ekVDc1J0
            eGRqU1lEQXpuZG1BaUx0RkQ2ejB1TVFva0NFCmFuWUVkM0c1c1F2QzRKOWhLOFNl
            b3l2bFBoMkZKZnZFY3FseFc1ajQ0N1UKLS0tIEQ2eUd3SFJZZlN4NWtra3pQSHJF
            QkJKcnVjODhDSFJkYUpVQWt4S3gyN1UKO7BRRNW4mSeyj/HMOuJCTTeVD0qLzvpZ
            92sFwIenQ3s2c0s3K7bbnlpJKQO+mYbh9oZUD5op7eW1QFPiKxfabg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbUFLeitiSTlZS2FnRWZK
            YmNrTGp2aW1VRm5reEg4eFRnbmZIa3FzV1dRCnJ2blAzSHdMMjhUa0hPSGtrOVVo
            dVBlNng0Qy9TcCtQNE1Iby9UL0IzNEEKLS0tIFF3SVdLSktRMjhkajRvSUNUN09E
            Q0hUZHZTTTE2V0FweE5jSGJSb1hCMG8KRRn1/xRgz8JetJkRhjWg2fuCg48EF+gP
            zhabPqLEBRTG0rBTgnaqsTn+i0o/Dsi2wHAtiDFLewpcfmgQV+5Yiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T22:13:40Z"
    mac: ENC[AES256_GCM,data:jvDna1BPV4Dk4VNk+vdwSNicO8PkXPs3L2et8sQQhUxDMlpWXmrdC0I2olN5MXjiYC32wygK5KSvtytKa+7jmdAjUktU1Rdiqc+BLSrd5xmOBytuo81ENKoRoBmO2KUnF8L0G5Z76aeA5F8vEUeKc+QUe0k0CoKx2bh9aa7OiBY=,iv:XyoBVN3LsBhIV38lvDqxmIssrenMya0BSswhoe0Uhok=,tag:77VMOHOZuztBzfSsiRmscQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId)$
    version: 3.9.0
