---
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ntfy-alertmanager.enc.yaml
  - ntfy-alertmanager-configmap.enc.yaml
