kind: Secret
type: Opaque
apiVersion: v1
metadata:
    name: smb-creds
    namespace: csi-smb-provisioner
data:
    domain: ""
    password: ENC[AES256_GCM,data:crZnwyZRq0cZdBAtxUFL5LDaw8mEPtKY,iv:DgvRxCACJIZllW5qhswBPX17f/3qp+krm3yPmz1NOHA=,tag:EoX9KHoBZXWrIdbtjnjl3w==,type:str]
    username: ENC[AES256_GCM,data:F9ILTYoPkIXl2sxd,iv:Vq7sE9Q+2xDWVX89GnFPPLgMPfyQ4MF80aRunSEI77E=,tag:U0V/Ze9kJ+DcxIjYW0SYfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxd1Y0SmdCT3FHQ2tRcHRI
            V0ZzK3BQT0d4QVpNM1d4dnFCci80b0c1UUVFCklLRFpSbUdMeW9TVHRvUlYxTU9l
            aGJoOTAySE1ySnR3ZWM5dkR2Slp5SEkKLS0tIDlDclpNYitySVhiTW9FMkkxN29x
            RHVRV1RZQjNVOWZnVVhvMkNWZ3YrQUUKuqVq/ekTmUGHhZXonL0NoKIBx49YRCJa
            YBXhM9SMiJ0iT1RlfPbd+i8UoajKwYSQs20nFzWBl5BHUkzZrQySnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaXNTd282K1hhbHZjTXFQ
            bzg3UGVsYXBqOGJsS28yaC9aOFFoaE5lQkZBCk56MkhSd3Vxcm4zK3EzQnhOVk9j
            QzdabzNEZWxHdXQ3bi9MY1FlNkZndWsKLS0tIFRJZ2ZUZFhnNVFaOW1OZGlKN1Fr
            NHVBS2JIY2tXUHg4N1Fnei8zdC9QbjQK0iv7DSprjU4FH8Nl1P7xuCW0D3m0+6sY
            1jNJBudtwvHc0c09R+zr3wHzFcylrLPkl2+EX7VDx3ykLvZkuVdIFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-24T20:33:35Z"
    mac: ENC[AES256_GCM,data:vj0bxYz/UMBsVKm9eBG4GnRyoQfknqjj+d9qXnhxDxUn49+efE4OShav96u6AFkCtiYEvKvh+WSoicuYvBtVeSlPSamKonP9Qz6/o3z48JFd6j4D3xqJ6T92/NIlPZpSfbc0/mds2FLZe/v2EXJ5yC0ffs8DaZcLmzPQWhzGAsc=,iv:dHju9cQWDGmXIDVyzES/b0pzRCdz9VLd1exnaFrXnm0=,tag:q5iuIUniwty/MaE21tutRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId)$
    version: 3.9.1
