---
commonAnnotations:
  argocd.argoproj.io/sync-wave: "09"

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 20.2.2
    releaseName: redis
    namespace: databases
    valuesFile: values.yaml
