apiVersion: v1
kind: Secret
metadata:
    name: paperless-env-secrets
type: Opaque
data:
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:7+F++0c4Yz71MIOF,iv:0x76VV2S7HbtLymN+fYc/VCg9XsfsRMr1hfryX3qxbY=,tag:+9uaR/d0Polco/a78lRENw==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:4jPEBZ1oAstDRBvRiUhNMOqldn+NvF8MWUZjb63tCFY=,iv:gX1ie+Gb65oqx369e+BapRnchT170Fl0SCHUrC6wCtA=,tag:SQXkOiw8XQEgvxMvgNMulA==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:liyscI7dQa9YnjY2aWekIR2sPpyLlDk4PJch6bvmn+frK3lFqDGXvQo3lhqaYdho,iv:6MY7lAHjqAEQaNZkDgei+wg0GQCsl7+6a1oLpsjnn4M=,tag:50tOsO7ugvpHzNTSzplAvw==,type:str]
    PAPERLESS_LOGOUT_REDIRECT_URL: ENC[AES256_GCM,data:pzLTeFVRnGlBLvsU+xKFJsVjwJ54PdjsGR+WpZGd/d6gQoRerDzjpQ==,iv:djJdf5jI4GXcIIIPeBCtYVqjEY8bqvK87IMvlia4i3A=,tag:llU1NBgwucjoVkVmmiq20A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQM2ROZFR1aDlnTG1BYThP
            dkJnWHZtelNlc3AwYzArYlllMVppcVJJRTBjCmtrRDRNWkJXZFBHdTlwMnM4YS92
            QWprWkl5TFY0RkErdnIvRW5MekdwVk0KLS0tIERVT2hMWE9SN1BwQzZTbko1Zzg1
            a3BrMGhFU0hvaDdOS3o1MExFdjZ1dWMKR6Gx2RPL8+PV+Mew0eDGB7RSijMTgdLj
            v2tKkiDEPQ/yJEfXLiE2tFqZ/C9lyP6sMFXsjPlrj0w2hvJOfGIIGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtYnpMY204RnNHQ3Rud3hW
            eEhlVXFVQ0wzRHVCbERMUWwvdmd3N1hsM1hFClJpQXBFOVpkUzVLdVc3MlVQdEZm
            WWRpMlJqTDk4OXJuNEFqT1hsSS9xMTQKLS0tIGdRVDRGNUlSZ04ydFlqY0Nta3My
            RGo2bTh1a0E0SitMVjFjakZjYmtqclUKutxgeXYbDHrH2PLawpCGz57HKzDMgoVa
            HnZcvpFmvh1l+DQ+HNwBpPkVc6SDzL6jGvcfb3kHr9SW1e6VcnD3LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T11:19:06Z"
    mac: ENC[AES256_GCM,data:RAcGAIMGaVYdcVvxhwci/0JqoOL9oDtuLE1OmzqlIwIJUf7HCsUjltp0TT+rza2LfJoZKSsegWQKvd5G7KAzsEsFVKOEpPdO8JBTITrkMwg5zwGFMxodo9bJAYsNafrzyztT/8Qqii+i2BBZPi6Rrk0NpYllUhlpSuXHfO0yshM=,iv:5YzGib3o7WhsVpu3s477oq4RhkAYDVbaZFGl6swmheQ=,tag:d1gauqnsPyosp6ynTTuHqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|securityTokenKey|emailRecipients)$
    version: 3.9.0
