image:
  repository: ghcr.io/paperless-ngx/paperless-ngx
  tag: 2.13.0
env:
  - name: TZ
    value: Europe/Berlin
  - name: PAPERLESS_TIME_ZONE
    value: Europe/Berlin
  - name: PAPERLESS_REDIS
    value: redis://redis-master.databases.svc.cluster.local:6379/2
  - name: PAPERLESS_DBENGINE
    value: mariadb
  - name: PAPERLESS_DBHOST
    value: mariadb.databases.svc.cluster.local
  - name: PAPERLESS_DBPORT
    value: 3306
  - name: PAPERLESS_DBSSLMODE
    value: PREFERRED
  - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
    value: true
  - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
    value: true
  #- name: PAPERLESS_ENABLE_HTTP_REMOTE_USER_API
  #  value: true
  - name: PAPERLESS_OCR_LANGUAGE
    value: deu
  - name: PAPERLESS_OCR_MODE
    value: skip
  - name: PAPERLESS_USE_X_FORWARD_HOST
    value: true
  - name: PAPERLESS_USE_X_FORWARD_PORT
    value: true
  - name: PAPERLESS_CONSUMER_RECURSIVE
    value: true
  - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
    value: true
  - name: PAPERLESS_CONSUMER_POLLING
    value: 300
  - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
    value: true
  - name: PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
    value: true
  - name: PAPERLESS_OCR_DESKEW
    value: true
persistentVolumeClaim:
  create: false
  storageClassName: longhorn
  existingPersistentVolumeClaim: smb-pvc-container-paperless-data
consumption:
  type: pvc
  persistentVolumeClaim:
    claimName: smb-pvc-documents
media:
  enabled: true
  type: pvc
  persistentVolumeClaim:
    claimName: smb-pvc-container-paperless-media
export:
  type: pvc
  persistentVolumeClaim:
    claimName: smb-pvc-container-paperless-export
trash:
  enabled: true
  type: pvc
  persistentVolumeClaim:
    claimName: smb-pvc-container-paperless-trash
