image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 2.13.4
env:
    - name: TZ
      value: Europe/Berlin
    - name: PAPERLESS_TIME_ZONE
      value: Europe/Berlin
    - name: PAPERLESS_REDIS
      value: redis://redis-master.databases.svc.cluster.local:6379/2
    - name: PAPERLESS_DBENGINE
      value: mariadb
    - name: PAPERLESS_DBHOST
      value: mariadb.databases.svc.cluster.local
    - name: PAPERLESS_DBPORT
      value: 3306
    - name: PAPERLESS_DBSSLMODE
      value: PREFERRED
    - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
      value: true
    - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
      value: true
    #- name: PAPERLESS_ENABLE_HTTP_REMOTE_USER_API
    #  value: true
    - name: PAPERLESS_OCR_LANGUAGE
      value: deu
    - name: PAPERLESS_OCR_MODE
      value: skip
    - name: PAPERLESS_USE_X_FORWARD_HOST
      value: true
    - name: PAPERLESS_USE_X_FORWARD_PORT
      value: true
    - name: PAPERLESS_CONSUMER_RECURSIVE
      value: true
    - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
      value: true
    - name: PAPERLESS_CONSUMER_POLLING
      value: 300
    - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
      value: true
    - name: PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
      value: true
    - name: PAPERLESS_OCR_DESKEW
      value: true
persistentVolumeClaim:
    create: false
    storageClassName: longhorn
    existingPersistentVolumeClaim: smb-pvc-container-paperless-data
consumption:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-documents
media:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-media
export:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-export
trash:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-trash
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UVpBWm0xUnVvYWI0c1Yw
            V0NNejM1MHRPelc1ZUh4MTUzNVI2QXpxSFJvCjVrdURKblZ2SDB0VzVHU2l1ZFFC
            NmZHY2JaYkY0YWR6d09NNWlDd0VyUU0KLS0tIGFMRnk4S0xaQ1ZBQmEzWjQxdEoy
            azdvcEoyS0x3bG5zWHVJTEZodHdZQ3cKkdBc1ZJFyeHu3JnuHBLc/1ADT6IJMYwS
            pGZ4SkBszV7Xb4JJ3UHpMbpX/aBZEOdDHxSr4/Vjoc1WkZoFhZeM4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUS9Oc2gyT2dvQWp3T3Y5
            TU9BTUlkMkVoTzIrZFdHa3V1QytLVUdRTXpJCkdTTE8vVFh3YkhZZmdKMXRjeUdi
            N1pQR015dU9yTWkrUlVDOE0wS05iU1EKLS0tIGg3NVdZeDRwU284d0V0eFBDclFQ
            UGdHVXJtYkk1enlEWEVSS1Vta2I5NjgKNskHnBmyqhA/kk40mHjXKDpH+wQWDEVV
            QqDJh+jB7zLKbzwDcfpMTUJJ0k7hhWfvc6N2AivMhXhykuXDCUmb8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T21:00:03Z"
    mac: ENC[AES256_GCM,data:kKqY9QxVBcnobR0cnavtMfxZig+cTY/KlFXJ8BV1Mley5uBsQLpDMKFBnDZVGN8NFqHLE6B3beUD2N4X8Hg+xaCAlqDyR+6qOk0y/bex804s9HY8UV1hu8YIy2b2zmrVoorazvIKv25PsW42PLcJudz537vYmQasudBXb1uN9xQ=,iv:94W34zUY29WPir5RVvcAKpmUlZZziV7TO0sjfH7/N9I=,tag:4YsSFcnryUY5NEZi7JDOgw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url|PIHOLE_DOMAIN|TUNNEL_DNS_UPSTREAM|customDnsEntries|securityTokenKey|emailRecipients)$
    version: 3.9.1
