image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    tag: 2.12.1
env:
    - name: TZ
      value: Europe/Berlin
    - name: PAPERLESS_TIME_ZONE
      value: Europe/Berlin
    - name: PAPERLESS_REDIS
      value: redis://redis-master.databases.svc.cluster.local:6379/2
    - name: PAPERLESS_DBENGINE
      value: mariadb
    - name: PAPERLESS_DBHOST
      value: mariadb.databases.svc.cluster.local
    - name: PAPERLESS_DBPORT
      value: 3306
    - name: PAPERLESS_DBSSLMODE
      value: PREFERRED
    - name: PAPERLESS_FILENAME_FORMAT_REMOVE_NONE
      value: true
    - name: PAPERLESS_ENABLE_HTTP_REMOTE_USER
      value: true
    #- name: PAPERLESS_ENABLE_HTTP_REMOTE_USER_API
    #  value: true
    - name: PAPERLESS_OCR_LANGUAGE
      value: deu
    - name: PAPERLESS_OCR_MODE
      value: skip
    - name: PAPERLESS_USE_X_FORWARD_HOST
      value: true
    - name: PAPERLESS_USE_X_FORWARD_PORT
      value: true
    - name: PAPERLESS_CONSUMER_RECURSIVE
      value: true
    - name: PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS
      value: true
    - name: PAPERLESS_CONSUMER_POLLING
      value: 300
    - name: PAPERLESS_CONSUMER_ENABLE_BARCODES
      value: true
    - name: PAPERLESS_CONSUMER_ENABLE_ASN_BARCODE
      value: true
    - name: PAPERLESS_OCR_DESKEW
      value: true
persistentVolumeClaim:
    create: false
    storageClassName: longhorn
    existingPersistentVolumeClaim: smb-pvc-container-paperless-data
consumption:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-documents
media:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-media
export:
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-export
trash:
    enabled: true
    type: pvc
    persistentVolumeClaim:
        claimName: smb-pvc-container-paperless-trash
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d2g7tgqpfvxulsusn3m608h60h2hne7yqwv5nh5nd24z6h0hgq0skjkhw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4amNsZkthWUU5cUR1TjVt
            d1gyK2RTL1E0aC9pbnV1YktrN0ovUnczbVJVCmtaWUp1TnJiT1FIZ2FGZk1ndHlY
            d2NsbDRtV0lkb1Z0dEdIM29jbDIzTGsKLS0tIEp6OUdXMHdHRHRhbXFjZDFJVVY2
            VWVvaDhUZkRmZ2srdEk5VjFnblZaV2cK+7LYiBc0tZ6t6+p8N5h9kd6n+fs5XhtH
            6zHffGlZkWO6ClXpU94xRu1neBOMP1cBxsaQ+qCigW24Kh5ItP5OjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1q522xtgjrmvr43w7um5rh02ta3yfns635680hz4m7uhw0nfqj5zqgxnz27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSnRYQmpZVjFVSlJRbGFh
            ZW12bUtuT0FoN0pVeDJpRnF6clI5VVNwQWxFCk91ODRoVmZHMDU0bG9pRW93U0I4
            TzV4dWgwQ09LQTA5NGpocVB4cWl3MDQKLS0tICtzeHQ3cFpPT0lxdWs0Unk5b0lQ
            bEdRK3dCQXJRbkw1U0FDRzU5WnNCb1EKWICa4QHsinmcSse82FoGfBO6dRh/jJT+
            sBG5tS+2UoWvFZtjnDP02/Ie6B/iv4OKah5hD9Ahio9X1vaTnkY+yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T11:01:05Z"
    mac: ENC[AES256_GCM,data:m3/4ygj7CyC8fyiDyW91wF38Hw5/ouqmOlD6IhJYUrqcf5Pu8NSxW6T/r81/tTRFFfXyFBzOwuQvm+jhN4t8VdvErBqzKeTWrFvSfISFrWxlXJlrJ0sEoCbMUA4wwq9a/mO28+IwTO9quxBot45yU6YoDh+ILfnPQH78Kymx1hc=,iv:7QnHpuhtjcRxRR8Nnwx9cgCnE44sTs+uBh1p5jKMqYY=,tag:Klo6swfU/UAY7ssoDa3cDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|email|dnsNames|.*(H|h)osts?|hostname|username|password|url|issuer|argocdServerAdminPassword|oidc.config|commonName|literals|.*awsAccessKeyId|.*awsSecretAccessKey|.*defaultAdminPassword|apiToken|accountId|rootPassword|replicationPassword|adminPassword|root_url|client_secret|auth_url|api_url)$
    version: 3.9.0
