---
name: Run renovatebot for updates

on:
  # Allows manual/automated ad-hoc trigger
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: "info"
        type: string
  schedule:
    - cron: "30 5,17 * * *"
concurrency: renovate
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Renovate JSON
        run: jq type .github/renovate.json
      - name: Run Renovate
        uses: renovatebot/github-action@v40.3.2
        with:
          configurationFile: ".github/renovate.json"
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ inputs.logLevel || 'info' }}
